<?php
/**
 * Created by PhpStorm.
 * User: zakrz
 * Date: 17.05.2016
 * Time: 21:24
 */

namespace merigold\przelewy24\src;


use yii\base\Model;

class Przelewy24Model extends Model
{

    public $p24_merchant_id;
    public $p24_pos_id;
    public $p24_session_id;
    public $p24_amount;
    public $p24_currency;
    public $p24_description;
    public $p24_email;
    public $p24_client;
    public $p24_address;
    public $p24_zip;
    public $p24_city;
    public $p24_country;
    public $p24_phone;
    public $p24_language;
    public $p24_method;
    public $p24_url_return;
    public $p24_url_status;
    public $p24_time_limit;
    public $p24_wait_for_result;
    public $p24_channel;
    public $p24_shipping;
    public $p24_transfer_label;
    public $p24_api_version;
    public $p24_sign;
    public $p24_encoding = 'UTF-8';
    public $p24_name_X;
    public $p24_description_X;
    public $p24_quantity_X;
    public $p24_price_X;
    public $p24_number_X;


    protected $chanels = [
        '1'=>'karty',
        '2'=>'przelewy',
        '4'=>'przelew tradycyjny',
        '16'=>'wszystkie 24/7',
        '32'=>'użyj przedpłatę'
    ];

    protected $CRC;

    /**
     * @param mixed $CRC
     */
    public function setCRC($CRC)
    {
        $this->CRC = $CRC;
    }


    public function rules()
    {
        return [
            [['p24_merchant_id','p24_pos_id','p24_session_id','p24_amount','p24_currency','p24_description','p24_email','p24_country','p24_url_return','p24_api_version','p24_sign'], 'required'],
            [
                [
                    'p24_merchant_id',
                    'p24_pos_id',
                    'p24_amount',
                    'p24_method',
                    'p24_time_limit',
                    'p24_wait_for_result',
                    'p24_channel',
                    'p24_shipping'
                ],
                'integer'
            ],
            [['p24_session_id', 'p24_sign'], 'string', 'max' => 100],
            [['p24_currency'], 'string', 'max' => 3],
            [['p24_description'], 'string', 'max' => 1024],
            [['p24_email', 'p24_client', 'p24_city'], 'string', 'max' => 50],
            [['p24_address'], 'string', 'max' => 80],
            [['p24_zip'], 'string', 'max' => 10],
            [['p24_country', 'p24_language'], 'string', 'max' => 2],
            [['p24_phone'], 'string', 'max' => 12],
            [['p24_url_return', 'p24_url_status'], 'string', 'max' => 250],
            [['p24_transfer_label'], 'string', 'max' => 20],
            [['p24_api_version'], 'string', 'max' => 5],
            [['p24_encoding'], 'string', 'max' => 15],
            ['p24_channel', 'in', 'range' => array_keys($this->chanels)],
            [['p24_name_X','p24_description_X'], 'each', 'rule' => ['string','max'=>127]],
            [['p24_quantity_X','p24_price_X','p24_number_X'], 'each', 'rule' => ['integer']]

        ];
    }

    public function afterValidate()
    {
        parent::afterValidate(); // TODO: Change the autogenerated stub

        $this->signForm();
    }

    private function signForm() {


        $sign = md5($this->p24_session_id."|".
            $this->p24_merchant_id."|".
            $this->p24_amount."|".
            $this->p24_currency."|".
            $this->CRC);

        $this->p24_sign = $sign;

    }


}