<?php

/**
 * Created by PhpStorm.
 * User: zakrz
 * Date: 05.05.2016
 * Time: 22:18
 */
class Przelewy24ComponentTest extends \merigold\przelewy24\tests\TestCase
{


    protected $errorResponse="error=1&errorMessage=jakiś tam tekst";
    protected $succesresponse="error=0&errorMessage=";
    protected $merchant_id = '11111';
    protected $CRC = '1111111';

    public function setUp()
    {
        parent::setUp();

        Yii::configure(Yii::$app, [
            'components' => [
                'user' => [
                    'class' => 'yii\web\User',
                    'identityClass' => 'common\models\User',
                ],
                'p24'=>[
                    'class'=>\merigold\przelewy24\src\Przelewy24Component::className(),
                    'merchant_id'=>$this->merchant_id,
                    'pos_id'=>$this->merchant_id,
                    'CRC'=>$this->CRC,
                ]
            ],

        ]);

        Yii::$container->set('HTTP_Request2', function () {

            $response = new HTTP_Request2_Response("HTTP/1.1 200 OK",true);
            $response->appendBody($this->succesresponse);

            $mockAdapter= new HTTP_Request2_Adapter_Mock();
            $mockAdapter->addResponse($response );

            $stub = new HTTP_Request2(\merigold\przelewy24\src\Przelewy24Component::TEST_URL,HTTP_Request2::METHOD_POST);
            $stub->setAdapter($mockAdapter);

            return $stub;
        });

    }

    public function testTestConnection()
    {

        $p24Connector = Yii::$app->p24;
        $result = $p24Connector->testConnection();
        $this->assertTrue($result,'Test connection should be success');

    }


    public function testModel()
    {
        $p24Connector = Yii::$app->p24;

        $model = $p24Connector->getModel();
        $this->assertInstanceOf(\merigold\przelewy24\src\Przelewy24Model::className(),$model,"should be in correct object");

    }


    public function testModelSign()
    {
        $p24Connector = Yii::$app->p24;

        $model = $p24Connector->getModel();
        $model->validate();


        $this->assertTrue($model->hasErrors(),'Model should not be valid');


        $sessionId = Yii::$app->session->id;
        $amout = null;
        $currency = null;
        $sign = md5($sessionId.'|'.$this->merchant_id."|".$amout."|".$currency."|".$this->CRC);


        $this->assertEquals($sign,$model->p24_sign,'sign form should be valid');



    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }





}
